const Router = require('express').Router()
const PostRouter = require('./PostRouter')
const UserRouter = require('./UserRouter')
const AuthRouter = require('./AuthRouter')
const CommentRouter = require('./CommentRouter')
const PostCommentRouter = require('./PostCommentRouter')
Router.use('/post', PostRouter)
Router.use('/user', UserRouter)
Router.use('/auth', AuthRouter)
Router.use('/comment', CommentRouter)
Router.use('/postcomment', PostCommentRouter)
module.exports = Router
